version: '3.7'

services:

  mongo-container:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - springBankNet

  mysql-container:
    container_name: mysql-container
    image: mysql:latest
    environment:
      - "MYSQL_ROOT_PASSWORD=springbankRootPsw"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_container:/var/lib/mysql
    networks:
      - springBankNet

  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
      - "ADMINER_DEFAULT_SERVER=mysql-container"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - springBankNet

  axon-server:
    container_name: axon-server
    image: axoniq/axonserver:latest
    restart: always
    ports:
      - "8024:8024"
      - "8124:8124"
    networks:
      - springBankNet

volumes:
  mongodb_data_container:
  mysql_data_container:

networks:
  springBankNet:
    driver: bridge