version: '3.7'

services:

  user-cmd-api:
    container_name: user-cmd-api
    image: user-cmd-api:latest
    networks:
      - springbankNet
    restart: always
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  user-query-api:
    container_name: user-query-api
    image: user-query-api:latest
    networks:
      - springbankNet
    restart: always
    ports:
      - "8082:8082"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  bankacc-cmd-api:
    container_name: bankacc-cmd-api
    image: bankacc-cmd-api:latest
    networks:
      - springbankNet
    restart: always
    ports:
      - "9091:9091"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  bankacc-query-api:
    container_name: bankacc-query-api
    image: bankacc-query-api:latest
    networks:
      - springbankNet
    restart: always
    ports:
      - "9092:9092"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    networks:
      - springbankNet
    restart: always
    ports:
      - "2000:2000"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  user-oauth2:
    container_name: user-oauth2
    image: user-oauth2:latest
    networks:
      - springbankNet
    restart: always
    ports:
      - "8084:8084"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  mongo-container:
    container_name: mongo-container
    image: mongo:latest
    networks:
      - springbankNet
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  mysql-container:
    container_name: mysql-container
    image: mysql:latest
    networks:
      - springbankNet
    environment:
      - "MYSQL_ROOT_PASSWORD=springbankRootPsw"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_container:/var/lib/mysql

  adminer:
    container_name: adminer
    image: adminer:latest
    networks:
      - springbankNet
    environment:
      - "ADMINER_DEFAULT_SERVER=mysql-container"
    restart: always
    ports:
      - "8080:8080"

  axon-server:
    container_name: axon-server
    image: axoniq/axonserver:latest
    networks:
      - springbankNet
    restart: always
    ports:
      - "8024:8024"
      - "8124:8124"

networks:
  springbankNet:
    external: false
    driver: bridge

volumes:
  mongodb_data_container:
  mysql_data_container: