version: '3.9'

services:

  user-cmd-api:
    container_name: user-cmd-api
    build: ./user-management/user.cmd.api
    image: user-cmd-api
    restart: always
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - db-axon-server_springBankNet

  user-query-api:
    container_name: user-query-api
    build: ./user-management/user.query.api
    image: user-query-api
    restart: always
    ports:
      - "8082:8082"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - db-axon-server_springBankNet

  bankacc-cmd-api:
    container_name: bankacc-cmd-api
    build: ./bank-account/bankacc.cmd.api
    image: bankacc-cmd-api
    restart: always
    ports:
      - "9091:9091"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - db-axon-server_springBankNet

  bankacc-query-api:
    container_name: bankacc-query-api
    build: ./bank-account/bankacc.query.api
    image: bankacc-query-api
    restart: always
    ports:
      - "9092:9092"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - db-axon-server_springBankNet

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    image: api-gateway
    restart: always
    ports:
      - "2000:2000"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - db-axon-server_springBankNet

  user-oauth2:
    container_name: user-oauth2
    build: ./user-management/user.oath2.0
    image: user-oauth2
    restart: always
    ports:
      - "8084:8084"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - db-axon-server_springBankNet

networks:
  db-axon-server_springBankNet:
    external: true