###
# Open Bank Account
POST /api/v1/openBankAccount
Host: localhost:2000
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "accountHolderId": "d322ffe8-3bc6-4821-9ebd-11d78c52fc92",
  "accountType": "CURRENT",
  "openingBalance": 100.0
}

###
# Deposit Funds
PUT /api/v1/depositFunds/e6d41467-2f37-4eaa-bb88-8c66ced26c1a
Host: localhost:2000
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "amount": 50.0
}

###
# Withdraw Funds
PUT /api/v1/withdrawFunds/e6d41467-2f37-4eaa-bb88-8c66ced26c1a
Host: localhost:2000
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "amount": 5.0
}


